name: ROS Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, lint_cmake]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: galactic
        linter: ${{ matrix.linter }}
        package-name:
          smacc2

          keyboard_client

          backward_global_planner
          backward_local_planner
          forward_global_planner
          forward_local_planner
          nav2z_planners_common
          pure_spinning_local_planner
          undo_path_global_planner
          nav2z_client

          multirole_sensor_client
          ros_publisher_client
          ros_timer_client

          eg_conditional_generator
          eg_random_generator

          smacc2_msgs

          sm_atomic
          sm_atomic_performance_test
          sm_atomic_subscribers_performance_test

          sr_all_events_go
          sr_conditional
          sr_event_countdown
